Resources:
  GatewayResponseDefault4XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Acces-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Acces-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_4XX
      RestApiId: 'ApiGatewayRestApi'
  GatewayResponseDefault5XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Acces-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Acces-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_5XX
      RestApiId: 'ApiGatewayRestApi'
